# Prefix / reload
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# Splits
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# Mouse mode
set -g mouse on

# Responsiveness
set -sg escape-time 0
set -g focus-events on

# Terminal / colors / clipboard
set -g default-terminal "tmux-256color"
set -as terminal-features ',*:RGB'
set -as terminal-features ',*:clipboard'
set -as terminal-features ',*:extkeys'

set -g set-clipboard on
set -g allow-passthrough on

# Status bar layout
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=black fg=white'

set -g status-left ''
set -g status-left-length 20
set -g status-right-length 50
set -g status-right '#[fg=#FFB38A] %H:%M:%S '

# Window status
setw -g window-status-style 'fg=white bg=black'
setw -g window-status-format ' #[fg=#FC305C]#I#[fg=white]:#W#[fg=#FF6E8B]#{?window_flags,#F,}#[fg=white] '

setw -g window-status-current-style 'fg=white bg=black bold'
setw -g window-status-current-format ' #[fg=#FC305C]#I#[fg=white]:#W#[fg=#FF6E8B]#{?window_flags,#F,}#[fg=white] '

# Pane borders
set -g pane-border-style fg="#8AC8FF"
set -g pane-active-border-style fg="#FC305C"

# Message / command prompt style
set -g message-style 'fg=black bg=#C9A3FF bold'
set -g message-command-style 'fg=black bg=#C9A3FF bold'

# Pane navigation
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Pane resizing
bind -r M-h resize-pane -L
bind -r M-l resize-pane -R
bind -r M-k resize-pane -U
bind -r M-j resize-pane -D
